import PropTypes from 'prop-types';
import styles from './About.module.css';
import apeAbout from '../../assets/apeAbout.png';
import Banner from '../Banner/Banner';
import { useOnDevice } from '../../hooks/useOnDevice.js';
import CrossAboutIcon from '../../icons/CrossAboutIcon.jsx';
import MenuButton from '../MenuButton/MenuButton.jsx';
const About = ({ aboutRef, goToHeader }) => {
  const onMobile = useOnDevice();
  const description =
    'EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS';
  const subTitle =
    '  WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT';
  return (
    <div ref={aboutRef} className={styles.wrap}>
      <div className={styles.inner}>
        <div className={styles.row}>
          <div className={styles.title}>
            <h2>
              A Story that started with <span>one simple ape</span>
            </h2>
          </div>
          {onMobile ? (
            <div className={styles.subTitle}>
              <p>{subTitle}</p>
            </div>
          ) : (
            <div className={styles.description}>
              <CrossAboutIcon />
              <p>{description}</p>
            </div>
          )}
        </div>
        <div className={styles.row}>
          {onMobile ? (
            <div className={styles.description}>
              <CrossAboutIcon />
              <p>{description}</p>
            </div>
          ) : (
            <div className={styles.descrWrap}>
              <div className={styles.subTitle}>
                <p>{subTitle}</p>
              </div>
              <div>
                <MenuButton onClick={goToHeader} className={styles.menuBtn} theme="white">
                  Menu
                </MenuButton>
              </div>
            </div>
          )}
          <div className={styles.imgWrap}>
            <img src={apeAbout} alt="ape" />
          </div>
        </div>
      </div>
      <Banner />
    </div>
  );
};

About.propTypes = {
  aboutRef: PropTypes.oneOfType([PropTypes.func, PropTypes.shape({ current: PropTypes.instanceOf(Element) })]),
  goToHeader: PropTypes.func,
};

export default About;

